sudo: required
services:
  - docker

before_install:
  - docker build -t anpopow/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true anpopow/react-test npm test -- --coverage

after_success:
  - docker build -t anpopow/multi-client ./client
  - docker build -t anpopow/multi-nginx ./nginx
  - docker build -t anpopow/multi-server ./server
  - docker build -t anpopow/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID --password-stdin
  - docker push anpopow/multi-client
  - docker push anpopow/multi-nginx
  - docker push anpopow/multi-server
  - docker push anpopow/multi-worker

branches:
  only:
  - master